mod alias;
mod branch;
mod clone;
mod commit;
mod diff;
mod reset;
mod stage;
mod sync;
mod unstage;
mod update;

pub use alias::{run_alias, run_unalias};
pub use branch::{create_branch, delete_branch, run_branch_interactive};
pub use clone::run_clone;
pub use commit::run_commit;
pub use diff::run_diff;
pub use reset::run_reset;
pub use stage::stage_targets;
pub use sync::{run_pull, run_push, run_sync};
pub use unstage::restore_stage;
pub use update::{check_and_auto_update, run_self_update};
